name: ml_kit
description: "ML Kits"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
